export enum ActionTypes {
  FETCH_DATA_ACTION = 'FETCH_DATA_ACTION'
}

export enum MutationTypes {
  FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS',
  FETCH_DATA_ERROR = 'FETCH_DATA_ERROR',
  SET_LOADER = 'SET_LOADER'
}
